# Generated by Django 5.2.8 on 2025-12-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('garland', 'Garland'), ('marriage', 'Marriage and Decoration for Marriage'), ('gods', 'Gods'), ('gods_decoration', 'Gods Garland and Decoration')], default='garland', max_length=20),
        ),
    ]
