# Generated by Django 5.2.8 on 2025-12-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('garland', 'Garland for Marriage'), ('marriage', 'Decoration for Marriage'), ('gods', 'Gods Decoration'), ('gods_decoration', 'Gods Garland ')], default='garland', max_length=20),
        ),
    ]
