# Generated by Django 6.0.3 on 2026-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'In Process'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('garland', 'Garland for Marriage'), ('marriage', 'Decoration for Marriage'), ('gods', 'Gods Decoration'), ('gods_decoration', 'Gods Garland '), ('others', 'Others')], default='garland', max_length=20),
        ),
    ]
